{
 "title": "Police UK Analyze",
 "time": { "from": "2019-12-31T23:00:00.000Z", "to": "2022-10-31T23:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "force_id",
    "label": "Commissariat",
    "query": "{\"find\" : \"terms\", \"field\" : \"force.keyword\"}"
   },
   {
    "name": "category",
    "label": "Catégorie",
    "query": "{\"find\":\"terms\", \"field\": \"category.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Statistiques sur les catégories de crimes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statistiques pour les crimes de type $category",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "repeat": "category",
     "targets": [
      {
       "bucketAggs": [
        {
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "category:$category",
       "timeField": "month"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistiques sur le commissariat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Statistiques des crimes répertoriées par le commissariat : $force_id",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "repeat": "force_id",
   "targets": [
    {
     "bucketAggs": [
      { "field": "month", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "force:$force_id",
     "timeField": "month"
    }
   ]
  },
  {
   "title": "Catégories des crimes répertoriées pour $force_id",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "repeat": "force_id",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "force:$force_id",
     "timeField": "month"
    }
   ]
  },
  {
   "title": "Statistiques globales",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 266 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statistiques sur les nombres de crimes répertoriées par mois",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "month",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "force:*",
       "timeField": "month"
      }
     ]
    },
    {
     "title": "Graphique sur les statistiques du nombre de crimes répertoriées par mois",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "*:*",
       "timeField": "month"
      }
     ]
    }
   ]
  }
 ]
}